//
//  VocabOverviewPresenter.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 13/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VocabOverviewPresentationLogic {
    func presentVocabOverview(response: VocabOverview.FetchVocabOverview.Response)
}

class VocabOverviewPresenter: VocabOverviewPresentationLogic {
    
    weak var viewController: VocabOverviewDisplayLogic?
    
    // MARK: Present VocabOverview
    
    func presentVocabOverview(response: VocabOverview.FetchVocabOverview.Response) {
        let viewModel = VocabOverview.FetchVocabOverview.ViewModel(vocabulary: response.vocabulary )
        viewController?.displayVocabOverview(viewModel: viewModel)
    }
}
