//
//  VocabOverviewRouter.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 13/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VocabOverviewRoutingLogic {
    func routeToNext()
}

protocol VocabOverviewDataPassing {
    var dataStore: VocabOverviewDataStore? { get }
}

class VocabOverviewRouter: NSObject, VocabOverviewRoutingLogic, VocabOverviewDataPassing {
    
    weak var viewController: VocabOverviewViewController?
    var dataStore: VocabOverviewDataStore?
    
    // MARK: Routing
    private var durationToWait: TimeInterval = 20 //todo move to config
    
    func routeToNext() {
        let destinationVC = FirstSceneViewController(nibName: nil, bundle: nil)
        StateKeeper.shared.setDidSeeDialog()
        StateKeeper.shared.setGameState(points: 0, storyLineId: "B3045_1", dialogIndex: 0, timeToWait: durationToWait)
        navigateToFirstScene(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToFirstScene(source: VocabOverviewViewController, destination: FirstSceneViewController) {
        source.show(destination, sender: nil)
    }
}
