//
//  VocabOverviewInteractor.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 13/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VocabOverviewBusinessLogic {
    func fetchVocabOverview(request: VocabOverview.FetchVocabOverview.Request)
}

protocol VocabOverviewDataStore {
    //var name: String { get set }
}

class VocabOverviewInteractor: VocabOverviewBusinessLogic, VocabOverviewDataStore {
    
    var presenter: VocabOverviewPresentationLogic?
    let worker = FirstSceneWorker()

    // MARK: Perform operation on VocabOverview
    
    func fetchVocabOverview(request: VocabOverview.FetchVocabOverview.Request) {
        // Perform network requests here and present afterwards
        guard let storyCollection = FirstSceneWorker.storyCollection else {
            return
        }
        let story = storyCollection.stories[0]
        
        let response = VocabOverview.FetchVocabOverview.Response(vocabulary: story.vocabulary )
        presenter?.presentVocabOverview(response: response)
    }
}
