//
//  VocabOverviewModels.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 13/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum VocabOverview {
    
    // MARK: Use cases
    
    enum FetchVocabOverview {
        
        struct Request {
            
        }
        
        struct Response {
            var vocabulary: [StoryContentText]
        }
        
        struct ViewModel {
            var vocabulary: [StoryContentText]
        }
    }
}
