//
//  VocabOverviewRouter.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 13/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VocabOverviewRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VocabOverviewDataPassing {
    var dataStore: VocabOverviewDataStore? { get }
}

class VocabOverviewRouter: NSObject, VocabOverviewRoutingLogic, VocabOverviewDataPassing {
    
    weak var viewController: VocabOverviewViewController?
    var dataStore: VocabOverviewDataStore?
    
    // MARK: Routing
    
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        }
//        else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
//
//    // MARK: Navigation
//
//    func navigateToSomewhere(source: VocabOverviewViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    // MARK: Passing data
//
//    func passDataToSomewhere(source: VocabOverviewDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
