//
//  FirstSceneWorker.swift
//  NewInTown
//
//  Created by Jan T on 09/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FirstSceneWorker {
    
    static var storyCollection: StoryCollection?
    
    func readJson() {
        guard let url = Bundle.main.url(forResource: "Stories", withExtension: "json") else {
            print("Missing stories file ...")
            return
        }

        do {
            let decoder = JSONDecoder()
            let data = try Data(contentsOf: url)
            let stories = try decoder.decode(StoryCollection.self, from: data)
            FirstSceneWorker.storyCollection = stories
        } catch {
            print("Reading stories failed ...")
        }
    }
    
    func getStoryLine(forId id: String) -> StoryLine? {
        guard let storyCollection = FirstSceneWorker.storyCollection else {
            return nil
        }
        for story in storyCollection.stories {
            for storyline in story.storylines {
                if storyline.id == id {
                    return storyline
                }
            }
        }
        return nil
    }
    
    func getDialog(forStoryLineId storyLineId: String, atIndex index: Int) -> Dialog? {
        guard let storyline = getStoryLine(forId: storyLineId) else {
            return nil
        }
        return storyline.dialogs[index]
    }

}
