//
//  FirstSceneWorker.swift
//  NewInTown
//
//  Created by Jan T on 09/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FirstSceneWorker {
    
    func getAnswer(forId id: AnswerId) -> String {
        switch id {
        case .chapter01Scence01Answer01:
            return "shi2"
        case .chapter01Scence01Answer02:
            return "ba1"
        }
    }
    
    func getQuestion(forId id: AnswerId) -> String {
        switch id {
        case .chapter01Scence01Answer01:
            return "How many dumplings would you like? Remember you usually eat 2 yourself and your friends asked you to bring 8. Write the answer in pinyin! (write with tones like yi1 (for one -)"
        case .chapter01Scence01Answer02:
            return "Oh, sorry it's late and we only have 8 left. So how many do you want?"
        }
    }
    
    func getNextQuestionId(forId id: AnswerId) -> AnswerId {
        guard let currentIndex = AnswerId.all.firstIndex(of: id) else {
            return id
        }
        let nextIndex = currentIndex + 1
        if nextIndex < AnswerId.all.count {
            return AnswerId.all[nextIndex]
        }
        return id
    }
}
