//
//  FirstSceneInteractor.swift
//  NewInTown
//
//  Created by Jan T on 09/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstSceneBusinessLogic {
    func validate(answer: String)
}

protocol FirstSceneDataStore {
    var currentScore: Int {get set}
}

class FirstSceneInteractor: FirstSceneBusinessLogic, FirstSceneDataStore {
    
    var presenter: FirstScenePresentationLogic?
    var currentScore: Int = 0
    var currentAnswerId: AnswerId = .chapter01Scence01Answer01

    let worker = FirstSceneWorker()
    
    // MARK: Perform operation on FirstScene

    func validate(answer: String) {
        var response = FirstScene.FetchFirstScene.Response()
        response.hasCorrectAnswer = worker.getAnswer(forId: currentAnswerId) == answer
        if response.hasCorrectAnswer {
            currentScore = currentScore + 10
            currentAnswerId = worker.getNextQuestionId(forId: currentAnswerId)
        } else {
            currentScore = currentScore - 5
        }
        response.score = currentScore
        response.nextId = currentAnswerId
        presenter?.updateFirstScene(response: response)
    }

}
