//
//  StoryPlaybackModels.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 11/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SoundPlaybackState {
    case stopped
    case playing
    case finished
}

enum LanguageSelection {
    case simplified
    case traditional
    case pinyin
    case english
}

enum StoryPlayback {
    
    // MARK: Use cases
    
    enum FetchStoryPlayback {
        
        struct Request {
            
        }
        
        struct Response {
            var playingState: SoundPlaybackState?
            var text: StoryContentText?
            var isDialogFinished: Bool?
            var languageSelection: LanguageSelection?
        }
        
        struct ViewModel {
            var playingState: SoundPlaybackState?
            var
            dialogText: String?
            var shouldShowNextButton: Bool
        }
    }
}
