//
//  StoryPlaybackRouter.swift
//  NewInTown
//
//  Created by Jan Trutzschler on 11/10/2018.
//  Copyright (c) 2018 teatracks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StoryPlaybackRoutingLogic {
    func routeToNext()
}

protocol StoryPlaybackDataPassing {
    var dataStore: StoryPlaybackDataStore? { get }
}

class StoryPlaybackRouter: NSObject, StoryPlaybackRoutingLogic, StoryPlaybackDataPassing {
    
    weak var viewController: StoryPlaybackViewController?
    var dataStore: StoryPlaybackDataStore?
    
    // MARK: Routing
    private var durationToWait: TimeInterval = 20 //todo move to config
    
    func routeToNext() {
        let destinationVC = FirstSceneViewController(nibName: nil, bundle: nil)
        StateKeeper.shared.setDidSeeDialog()
        StateKeeper.shared.setGameState(points: 0, storyLineId: "B3045_1", dialogIndex: 0, timeToWait: durationToWait)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSomewhere(source: StoryPlaybackViewController, destination: FirstSceneViewController) {
        source.show(destination, sender: nil)
    }

}
